print("=== Тестування методів списків ===")
list = [1, 5, 7]
print('Початковий список: ', list)
list.extend([4, 2])
print('extend([4, 2]):    ', list)
list.append(3)
print('append(3):         ', list)
list.insert(1,1)
print('insert(1,1):       ', list)
list.remove(1)
print('remove(1):         ', list)
list.sort()
print('sort():            ', list)
list.reverse()
print('reverse():         ', list)
list_copy = list.copy()
print("copy():            ", list_copy)
list.clear()
print('clear():           ', list)
